-- 地址表
CREATE TABLE ADDRESS (
	`ID` INT (12) PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT '主键id',
	`NAME` VARCHAR (50) NOT NULL COMMENT '关键词名称',
	`OLD_NAME` VARCHAR (50) COMMENT '关键词前名称',
	`STATUS` INT (2) NOT NULL COMMENT '状态（是否启用）',
	`ADDRESS_TYPE_ID` INT (2) COMMENT 'a',
	`ADDRESS_LEVEL` INT (2) COMMENT '关键词级别(国、省、市、区/县、街道等)',
	`PARENT_ID` INT (12) COMMENT '关键词父节点id',
	`PATH` VARCHAR (100) COMMENT '关键词路径',
	`INDEXED` INT (1) COMMENT '生成索引标志',
	`CREATION_TIME` DATETIME COMMENT '创建时间'
) ENGINE = INNODB DEFAULT CHARSET = utf8 COLLATE = utf8_bin COMMENT '地址表';

-- create index IDX_ADDRESS_NAME
CREATE INDEX `IDX_ADDRESS_NAME` ON `ADDRESS`
(
	NAME
);

-- create index IDX_ADDRESS_PARENT_ID
CREATE INDEX `IDX_ADDRESS_PARENT_ID` ON `ADDRESS`
(
	PARENT_ID
);

-- 地址权限表
CREATE TABLE ADDRESS_PERMISSIONS (
	`ID` INT (12) PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT '主键id',
	`ADDRESS_ID` INT (12) NOT NULL COMMENT '关键词id',
	`CUSTOMER_ID` INT (12) COMMENT '客户id'
) ENGINE = INNODB DEFAULT CHARSET = utf8 COLLATE = utf8_bin COMMENT '地址权限表';

CREATE INDEX `IDX_ADDRESS_PERMISSION_ADDRESS_ID` ON `ADDRESS_PERMISSIONS`
(
	`ADDRESS_ID`
);

-- 地址别名表
CREATE TABLE ALIAS (
	`ID` INT (12) PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT '主键id',
	`ADDRESS_ID` INT (12) NOT NULL COMMENT '关键词id', 
	`CUSTOMER_ID` INT (12) COMMENT '客户id',
	`NAME` VARCHAR (50) NOT NULL COMMENT '别名',
	`OLD_NAME` VARCHAR (50) COMMENT '前别名'
) ENGINE = INNODB DEFAULT CHARSET = utf8 COLLATE = utf8_bin COMMENT '地址别名表';

-- 系统配置
CREATE TABLE `SYSTEM_CONFIG` (
	`ID` INT (12) PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT '主键id',
	`NAME` VARCHAR(60) NOT NULL COMMENT '参数名称',
	`VALUE` VARCHAR(32) DEFAULT NULL COMMENT '参数值',
	`DESCRIPTION` VARCHAR(100) DEFAULT NULL COMMENT '参数的描述',
	`EDITABLE` INT(1) COMMENT 'a'
) ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT '系统配置表';

-- 客户
-- DROP TABLE customers;
CREATE TABLE CUSTOMERS (
	`ID` INT (12) PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT '主键id',
	`NAME` VARCHAR (20) NOT NULL COMMENT '客户名称',
	`STATUS` INT (2) COMMENT '状态标识（是否启用）',
	`DESCRIPTION` VARCHAR (200) COMMENT '描述'
) ENGINE = INNODB DEFAULT CHARSET = utf8 COLLATE = utf8_bin COMMENT '客户信息表';

-- 配送站点与地址关系
CREATE TABLE ADDRESS_STATION_RELATION (
	`ID` INT (12) PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT '主键id',
	`ADDRESS_ID` INT (12) NOT NULL COMMENT '关键词id',
	`DELIVERY_STATION_ID` INT (12) NOT NULL COMMENT '配送站点id'
) ENGINE = INNODB DEFAULT CHARSET = utf8 COLLATE = utf8_bin COMMENT '配送站点与地址关系表';

-- 客户端应用
CREATE TABLE CLIENT_APPLICATIONS (
	`ID` INT (12) PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT '主键id',
	`NAME` VARCHAR (32) NOT NULL COMMENT '登录名',
	`PASSWORD` VARCHAR (32) NOT NULL COMMENT '登陆密码',
	`CUSTOMER_ID` INT (12) NOT NULL COMMENT '客户id',
	`STATUS` INT (2) COMMENT '状态标识（是否启用）'
) ENGINE = INNODB DEFAULT CHARSET = utf8 COLLATE = utf8_bin COMMENT '客户端应用表';

-- 配送站点
CREATE TABLE DELIVERY_STATIONS (
	`ID` INT (12) PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT '主键id',
	`NAME` VARCHAR (20) NOT NULL COMMENT '站点名称',
	`EXTERNAL_ID` INT (12) NOT NULL COMMENT 'a',
	`CUSTOMER_ID` INT (12) NOT NULL COMMENT '客户id',
	`STATUS` INT (2) NOT NULL COMMENT '状态标识（是否启用）',
	`CREATION_TIME` DATETIME COMMENT '创建时间'
) ENGINE = INNODB DEFAULT CHARSET = utf8 COLLATE = utf8_bin COMMENT '配送站点表';

-- create index IDX_DELIVERY_STATION_EXTERNAL_ID
CREATE UNIQUE INDEX `IDX_DELIVERY_STATION_EXTERNAL_ID` ON `DELIVERY_STATIONS`
(
	EXTERNAL_ID,
	CUSTOMER_ID
);

-- 配送员表
-- DROP TABLE DELIVERERS;
CREATE TABLE DELIVERERS (
	`ID` INT (12) PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT '主键id',
	`NAME` VARCHAR (50) COMMENT '配送员名称',
	`EXTERNAL_ID` INT (12) NOT NULL COMMENT 'a',
	`CUSTOMER_ID` INT (12) NOT NULL COMMENT '客户id',
	`STATUS` INT (2) NOT NULL COMMENT '状态标识（是否启用）',
	`CREATION_TIME` DATETIME COMMENT '创建时间'
) ENGINE = INNODB DEFAULT CHARSET = utf8 COLLATE = utf8_bin COMMENT '配送员信息表';

CREATE UNIQUE INDEX `IDX_DELIVERER_CUSTOMER` ON `DELIVERERS`
(
	EXTERNAL_ID,
	CUSTOMER_ID
);

-- 供货商表
-- DROP TABLE VENDORS;
CREATE TABLE VENDORS (
	`ID` INT (12) PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT '主键id',
	`NAME` VARCHAR (50) COMMENT '供货商名称',
	`EXTERNAL_ID` INT (12) NOT NULL COMMENT 'a',
	`CUSTOMER_ID` INT (12) NOT NULL COMMENT '客户id',
	`STATUS` INT (2) NOT NULL COMMENT '状态标识（是否启用）',
	`CREATION_TIME` DATETIME COMMENT '创建时间'
) ENGINE = INNODB DEFAULT CHARSET = utf8 COLLATE = utf8_bin COMMENT '供货商表';

CREATE UNIQUE INDEX `IDX_VENDOR_CUSTOMER_VENDOR` ON `VENDORS`
(
	EXTERNAL_ID,	
	CUSTOMER_ID
);

-- 地址导入结果表
-- DROP TABLE ADDRESS_IMPORT_RESULTS;
CREATE TABLE ADDRESS_IMPORT_RESULTS (
	`ID` INT (12) PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT '主键id',
	`USER_ID` INT (12) COMMENT '用户id',
	`SUCCESS_COUNT` INT (12) COMMENT '成功个数',
	`FAILURE_COUNT` INT (12) COMMENT '失败个数',
	`IMPORT_DATE` DATETIME COMMENT '导入时间'
) ENGINE = INNODB DEFAULT CHARSET = utf8 COLLATE = utf8_bin COMMENT '地址导入结果表';

CREATE INDEX `IDX_ADDRESS_IMPORT_RESULTS_USER` ON `ADDRESS_IMPORT_RESULTS`
(
	USER_ID
);

-- 地址导入结果明细表
-- DROP TABLE ADDRESS_IMPORT_DETAILS;
CREATE TABLE ADDRESS_IMPORT_DETAILS (
	`ID` INT (12) PRIMARY KEY NOT NULL AUTO_INCREMENT  COMMENT '主键id',
	`RESULT_ID` INT (12)  COMMENT '导入结果id',
	`ADDRESS_ID` INT (12)  COMMENT '关键词id',
	`STATUS` INT (2)  COMMENT '状态',
	`MESSAGE` VARCHAR (50)  COMMENT '导入结果信息',
	`PROVINCE` VARCHAR (20)  COMMENT '导入的省',
	`CITY` VARCHAR (20) COMMENT '导入的市',
	`DISTRICT` VARCHAR (20) COMMENT '导入的区',
	`ADDRESS1` VARCHAR (50) COMMENT '关键词1',
	`ADDRESS2` VARCHAR (50) COMMENT '关键词2',
	`ADDRESS3` VARCHAR (50) COMMENT '关键词3',
	`DELIVERY_STATION_ID` INT (12) COMMENT '配送站点id',
	`DELIVERY_STATION_NAME` VARCHAR (20) COMMENT '配送站点名称',
	`DELIVERER_ID` INT (12)  COMMENT '配送员id',
	`DELIVERER_NAME` VARCHAR (20) COMMENT '配送员名称'
) ENGINE = INNODB DEFAULT CHARSET = utf8 COLLATE = utf8_bin COMMENT '地址导入结果明细表';

CREATE INDEX `IDX_ADDRESS_IMPORT_DETAILS_RESULT_ID` ON `ADDRESS_IMPORT_DETAILS`
(
	RESULT_ID
);

-- 用户表
-- DROP TABLE USERS;
CREATE TABLE USERS (
  `ID` INT (12) PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `NAME` VARCHAR (20) COMMENT '用户名称',
  `PASSWORD` VARCHAR (20) COMMENT '登录密码',
  `STATUS` INT (2) COMMENT '状态标识（是否启用）',
  `CUSTOMER_ID` INT (12) COMMENT '客户id'
) ENGINE = INNODB DEFAULT CHARSET = utf8 COLLATE = utf8_bin COMMENT '用户表';

CREATE UNIQUE INDEX `IDX_USER_NAME` ON `USERS`
(
	NAME
);

-- 站点规则
-- DROP TABLE DELIVERY_STATION_RULES;
CREATE TABLE DELIVERY_STATION_RULES (
	`ID` INT (12) PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT '主键id',
	`RULE` VARCHAR (100) COMMENT 'a',
	`RULE_EXPRESSION` VARCHAR (1000) COMMENT '规则表达式',
	`RULE_TYPE` INT (2) NOT NULL COMMENT '规则类型',
	`ADDRESS_ID` INT (12) NOT NULL COMMENT '关键词id',
	`DELIVERY_STATION_ID` INT (12) NOT NULL COMMENT '配送站点id',
	`CREATION_TIME` DATETIME COMMENT '创建时间'
) ENGINE = INNODB DEFAULT CHARSET = utf8 COLLATE = utf8_bin COMMENT '站点规则表';

-- create index IDX_DS_RULE_ADDRESS_ID
CREATE INDEX `IDX_DS_RULE_ADDRESS_ID` ON `DELIVERY_STATION_RULES`
(
	ADDRESS_ID
);


-- 配送员规则
-- DROP TABLE DELIVERER_RULES;
CREATE TABLE DELIVERER_RULES (
	`ID` INT (12) PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT '主键id',
	`RULE` VARCHAR (100) COMMENT 'a',
	`RULE_EXPRESSION` VARCHAR (1000) COMMENT '规则表达式',
	`RULE_TYPE` INT (2) NOT NULL COMMENT '规则类型',
	`ADDRESS_ID` INT (12) NOT NULL COMMENT '关键词id',
	`DELIVERER_ID` INT (12) NOT NULL COMMENT '配送员id',
	`CREATION_TIME` DATETIME  COMMENT '创建时间'
) ENGINE = INNODB DEFAULT CHARSET = utf8 COLLATE = utf8_bin COMMENT '配送员规则表';

-- create index IDX_DELIVERER_RULE_ADDRESS_ID
CREATE INDEX `IDX_DELIVERER_RULE_ADDRESS_ID` ON `DELIVERER_RULES`
(
	ADDRESS_ID
);

