-- 地址表
CREATE TABLE ADDRESS (
	`ID` INT (12) PRIMARY KEY NOT NULL AUTO_INCREMENT,
	`NAME` VARCHAR (50) NOT NULL,
	`OLD_NAME` VARCHAR (50),
	`STATUS` INT (2) NOT NULL,
	`ADDRESS_TYPE_ID` INT (2),
	`ADDRESS_LEVEL` INT (2),
	`PARENT_ID` INT (12),
	`PATH` VARCHAR (100),
	`INDEXED` INT (1),
	`CREATION_TIME` DATETIME
) ENGINE = INNODB DEFAULT CHARSET = utf8 COLLATE = utf8_bin;

-- create index IDX_ADDRESS_NAME
CREATE INDEX `IDX_ADDRESS_NAME` ON `ADDRESS`
(
	NAME
);

-- create index IDX_ADDRESS_PARENT_ID
CREATE INDEX `IDX_ADDRESS_PARENT_ID` ON `ADDRESS`
(
	PARENT_ID
);

-- 地址权限表
CREATE TABLE ADDRESS_PERMISSIONS (
	`ID` INT (12) PRIMARY KEY NOT NULL AUTO_INCREMENT,
	`ADDRESS_ID` INT (12) NOT NULL,
	`CUSTOMER_ID` INT (12)
) ENGINE = INNODB DEFAULT CHARSET = utf8 COLLATE = utf8_bin;

CREATE INDEX `IDX_ADDRESS_PERMISSION_ADDRESS_ID` ON `ADDRESS_PERMISSIONS`
(
	`ADDRESS_ID`
);

-- 地址别名表
CREATE TABLE ALIAS (
	`ID` INT (12) PRIMARY KEY NOT NULL AUTO_INCREMENT,
	`ADDRESS_ID` INT (12) NOT NULL,
	`CUSTOMER_ID` INT (12),
	`NAME` VARCHAR (50) NOT NULL,
	`OLD_NAME` VARCHAR (50)
) ENGINE = INNODB DEFAULT CHARSET = utf8 COLLATE = utf8_bin;

-- 系统配置
CREATE TABLE `SYSTEM_CONFIG` (
	`ID` INT (12) PRIMARY KEY NOT NULL AUTO_INCREMENT,
	`NAME` VARCHAR(60) NOT NULL,
	`VALUE` VARCHAR(32) DEFAULT NULL,
	`DESCRIPTION` VARCHAR(100) DEFAULT NULL,
	`EDITABLE` INT(1)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

-- 客户
-- DROP TABLE customers;
CREATE TABLE CUSTOMERS (
	`ID` INT (12) PRIMARY KEY NOT NULL AUTO_INCREMENT,
	`NAME` VARCHAR (20) NOT NULL,
	`STATUS` INT (2),
	`DESCRIPTION` VARCHAR (200)
) ENGINE = INNODB DEFAULT CHARSET = utf8 COLLATE = utf8_bin;

-- 配送站点与地址关系
CREATE TABLE ADDRESS_STATION_RELATION (
	`ID` INT (12) PRIMARY KEY NOT NULL AUTO_INCREMENT,
	`ADDRESS_ID` INT (12) NOT NULL,
	`DELIVERY_STATION_ID` INT (12) NOT NULL
) ENGINE = INNODB DEFAULT CHARSET = utf8 COLLATE = utf8_bin;

-- 客户端应用
CREATE TABLE CLIENT_APPLICATIONS (
	`ID` INT (12) PRIMARY KEY NOT NULL AUTO_INCREMENT,
	`NAME` VARCHAR (32) NOT NULL,
	`PASSWORD` VARCHAR (32) NOT NULL,
	`CUSTOMER_ID` INT (12) NOT NULL,
	`STATUS` INT (2)
) ENGINE = INNODB DEFAULT CHARSET = utf8 COLLATE = utf8_bin;

-- 配送站点
CREATE TABLE DELIVERY_STATIONS (
	`ID` INT (12) PRIMARY KEY NOT NULL AUTO_INCREMENT,
	`NAME` VARCHAR (20) NOT NULL,
	`EXTERNAL_ID` INT (12) NOT NULL,
	`CUSTOMER_ID` INT (12) NOT NULL,
	`STATUS` INT (2) NOT NULL,
	`CREATION_TIME` DATETIME
) ENGINE = INNODB DEFAULT CHARSET = utf8 COLLATE = utf8_bin;

-- create index IDX_DELIVERY_STATION_EXTERNAL_ID
CREATE UNIQUE INDEX `IDX_DELIVERY_STATION_EXTERNAL_ID` ON `DELIVERY_STATIONS`
(
	EXTERNAL_ID,
	CUSTOMER_ID
);

-- 配送员表
-- DROP TABLE DELIVERERS;
CREATE TABLE DELIVERERS (
	`ID` INT (12) PRIMARY KEY NOT NULL AUTO_INCREMENT,
	`NAME` VARCHAR (50),
	`EXTERNAL_ID` INT (12) NOT NULL,
	`CUSTOMER_ID` INT (12) NOT NULL,
	`STATUS` INT (2) NOT NULL,
	`CREATION_TIME` DATETIME
) ENGINE = INNODB DEFAULT CHARSET = utf8 COLLATE = utf8_bin;

CREATE UNIQUE INDEX `IDX_DELIVERER_CUSTOMER` ON `DELIVERERS`
(
	EXTERNAL_ID,
	CUSTOMER_ID
);

-- 供货商表
-- DROP TABLE VENDORS;
CREATE TABLE VENDORS (
	`ID` INT (12) PRIMARY KEY NOT NULL AUTO_INCREMENT,
	`NAME` VARCHAR (50),
	`EXTERNAL_ID` INT (12) NOT NULL,
	`CUSTOMER_ID` INT (12) NOT NULL,
	`STATUS` INT (2) NOT NULL,
	`CREATION_TIME` DATETIME
) ENGINE = INNODB DEFAULT CHARSET = utf8 COLLATE = utf8_bin;

CREATE UNIQUE INDEX `IDX_VENDOR_CUSTOMER_VENDOR` ON `VENDORS`
(
	EXTERNAL_ID,	
	CUSTOMER_ID
);

-- 地址导入结果表
-- DROP TABLE ADDRESS_IMPORT_RESULTS;
CREATE TABLE ADDRESS_IMPORT_RESULTS (
	`ID` INT (12) PRIMARY KEY NOT NULL AUTO_INCREMENT,
	`USER_ID` INT (12),
	`SUCCESS_COUNT` INT (12),
	`FAILURE_COUNT` INT (12),
	`IMPORT_DATE` DATETIME
) ENGINE = INNODB DEFAULT CHARSET = utf8 COLLATE = utf8_bin;

CREATE INDEX `IDX_ADDRESS_IMPORT_RESULTS_USER` ON `ADDRESS_IMPORT_RESULTS`
(
	USER_ID
);

-- 地址导入结果明细表
-- DROP TABLE ADDRESS_IMPORT_DETAILS;
CREATE TABLE ADDRESS_IMPORT_DETAILS (
	`ID` INT (12) PRIMARY KEY NOT NULL AUTO_INCREMENT,
	`RESULT_ID` INT (12),
	`ADDRESS_ID` INT (12),
	`STATUS` INT (2),
	`MESSAGE` VARCHAR (50),
	`PROVINCE` VARCHAR (20),
	`CITY` VARCHAR (20),
	`DISTRICT` VARCHAR (20),
	`ADDRESS1` VARCHAR (50),
	`ADDRESS2` VARCHAR (50),
	`ADDRESS3` VARCHAR (50),
	`DELIVERY_STATION_ID` INT (12),
	`DELIVERY_STATION_NAME` VARCHAR (20),
	`DELIVERER_ID` INT (12),
	`DELIVERER_NAME` VARCHAR (20)
) ENGINE = INNODB DEFAULT CHARSET = utf8 COLLATE = utf8_bin;

CREATE INDEX `IDX_ADDRESS_IMPORT_DETAILS_RESULT_ID` ON `ADDRESS_IMPORT_DETAILS`
(
	RESULT_ID
);

-- 用户表
-- DROP TABLE USERS;
CREATE TABLE USERS (
  `ID` INT (12) PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR (20),
  `PASSWORD` VARCHAR (20),
  `STATUS` INT (2),
  `CUSTOMER_ID` INT (12)
) ENGINE = INNODB DEFAULT CHARSET = utf8 COLLATE = utf8_bin;

CREATE UNIQUE INDEX `IDX_USER_NAME` ON `USERS`
(
	NAME
);

-- 站点规则
-- DROP TABLE DELIVERY_STATION_RULES;
CREATE TABLE DELIVERY_STATION_RULES (
	`ID` INT (12) PRIMARY KEY NOT NULL AUTO_INCREMENT,
	`RULE` VARCHAR (100) NOT NULL,
	`RULE_TYPE` INT (2) NOT NULL,
	`STATUS` INT (2) NOT NULL,
	`ADDRESS_ID` INT (12) NOT NULL,
	`CUSTOMER_ID` INT (12) NOT NULL,
	`CREATION_TIME` DATETIME
) ENGINE = INNODB DEFAULT CHARSET = utf8 COLLATE = utf8_bin;

-- create index IDX_DS_RULE_ADDRESS_ID
CREATE INDEX `IDX_DS_RULE_ADDRESS_ID` ON `DELIVERY_STATION_RULES`
(
	ADDRESS_ID
);

